# Generated by Django 2.1.5 on 2019-09-29 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colloc', '0002_auto_20190929_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison', models.TextField(blank=True, null=True)),
                ('collocDonneur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collocDonneur', to='colloc.Person')),
                ('collocReceveur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collocReceveur', to='colloc.Person')),
            ],
        ),
    ]
