# Generated by Django 2.1.5 on 2019-09-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colloc', '0004_auto_20190929_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['date'], 'verbose_name': 'Transaction'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
