# Generated by Django 2.1.5 on 2019-09-29 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colloc', '0005_auto_20190929_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
