# Generated by Django 2.1.5 on 2019-09-29 15:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('colloc', '0009_auto_20190929_1459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['date'], 'verbose_name': 'Transaction'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 9, 29, 15, 9, 21, 940157, tzinfo=utc), null=True),
        ),
    ]
