# Generated by Django 2.1.5 on 2019-09-29 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colloc', '0011_auto_20190929_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Transaction'},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='date',
        ),
    ]
